[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytorch_tutorials_and_playground"
version = "2024.0.0"
dependencies = ["numpy", "matplotlib", "torch", "ruff"]
requires-python = ">=3.10"
